schema_version: 20180708
name: go-plugin-func
version: 0.0.52
runtime: go
build_image: golang:1.11.1-stretch
run_image: debian:stretch
entrypoint: ./func
format: http-stream
triggers:
- name: go-plugin-func-trigger
  type: http
  source: /go-plugin-func-trigger
